### ISSUE TITLE
Add explanatory footer

### ISSUE THREAD

**Issue by davelab6** [lemzwerg/noto-hinted#1]
On the pages like https://rawgit.com/lemzwerg/noto-hinted/master/NotoSerifLao/index.html please add a footer that says

> Tips:
> 
> The filenames indicate the TTFAutohint mode used: -G- means strong hinting for GDI ClearType only, while -gGD- indicates strong hinting for all hinting modes (grayscale, GDI, and DWrite ClearType).
> 
> Take care when looking at the PNGs using Mac Retina or other hi-dpi screens to prevent the browser extrapolating the image to the higher resolution of the screen.

Thanks to @brawer for these tips :)

**Comment by lemzwerg** [comment]
Thanks, done!
